# Generated by Django 5.1.5 on 2025-01-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full time', 'Full time'), ('part time', 'Part time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
